---
development:
  cloud_name: dzozopar1
  api_key: '835645413828828'
  api_secret: nklPUtL3b_QPZABn1-v10fjluZQ
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dzozopar1
  api_key: '835645413828828'
  api_secret: nklPUtL3b_QPZABn1-v10fjluZQ
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dzozopar1
  api_key: '835645413828828'
  api_secret: nklPUtL3b_QPZABn1-v10fjluZQ
  enhance_image_tag: true
  static_image_support: false
