---
development:
  cloud_name: 
  api_key: 
  api_secret: 
  enhance_image_tag: 
  static_image_support: 
production:
  cloud_name: <%= ENV['CLOUDINARY_CLOUD_NAME'] %>
  api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dzozopar1
  api_key: 835645413828828
  api_secret: nklPUtL3b_QPZABn1-v10fjluZQ
  enhance_image_tag: true
  static_image_support: false
