---
development:
  cloud_name: dqjmmab0f
  api_key: '465442482381634'
  api_secret: yhKGPiLMSg-heRpB4bRI7TpPBvE
  enhance_image_tag: true
  static_image_support: true
production:
  cloud_name: dqjmmab0f
  api_key: '465442482381634'
  api_secret: yhKGPiLMSg-heRpB4bRI7TpPBvE
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dqjmmab0f
  api_key: '465442482381634'
  api_secret: yhKGPiLMSg-heRpB4bRI7TpPBvE
  enhance_image_tag: true
  static_image_support: false
